 protected void setException(Throwable t) { setFailed(t); } 