public void fail(Exception theException, String theMessage) { try{ } catch (Exception e) { } System.exit(1); } 